---
abstract: 'which is self fastest?'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Acme-SelfBenchmark
no_index:
  directory:
    - inc
    - t
requires:
  Attribute::Method: 1.01
  Benchmark: 1.07
  File::Spec: 3.2701
  FindBin: 1.47
  Module::Find: 0.06
  Spiffy: 0.3
  perl: 5.8.0
  self: 0.15
  selfvars: 0.1
tests: 't/*.t t/*/*.t t/*/*/*.t'
version: 0.01
